### ISSUE TITLE
A HUGE wave of errors after quick load

### ISSUE THREAD

**Issue by YuLun-bili** [evs-dev/Teardown-FPSCounter#2]
![image](https://user-images.githubusercontent.com/70589524/118025109-5be20d80-b357-11eb-8a83-b9eafd0e56a7.png)

**Comment by evs-dev** [comment]
Thanks for reporting! I'm having a look now.

**Comment by evs-dev** [comment]
Thanks again for the report. I hadn't even considered testing quick save/load. All should be fixed now I hope!
